apiVersion: v1
kind: Depployment
metadata: 
  name: php-apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-apache
  template:
    metadata:
      labels:
        app: php-apache
    specs:
      containers:
        - name: php-apache
          image: awanpk/farmers-portal:latest
          port: 
            - containerPort: 8080
          env:
          name: DB_HOST
          value: db
          name: DB_USERNAME
          value: root
          name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: php-service
spec:
  type: NodePort
  selector:
    app: php-apache
  ports:
    - port: 80
      targetPort: 80
      NodePort: 300001
