apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: farmers-portal-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"  
   # cert-manager.io/cluster-issuer: "letsencrypt-production"
    acme.cert-manager.io/http01-edit-in-place: "true"  
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - farmers.itsmuhammadbilal.me
      secretName: farmers-portal-tls-secret
  rules:
    - host: farmers.itsmuhammadbilal.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: farmers-portal-service
                port:
                  number: 80
